# Generated by Django 4.1.7 on 2023-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
